#include "../../1-LIB/STD_TYPES.h"
#include "../../1-LIB/BIT_MATH.h"

#include "ADC_interface.h"
#include "ADC_private.h"
#include "ADC_config.h"

void ADC_init(void)
{
	ADMUX=0;
	#if REFERENCE_SELECTION == AREF
	    CLR_BIT(ADMUX,REFS0);
		CLR_BIT(ADMUX,REFS1);
    #elif REFERENCE_SELECTION == AVCC
	    SET_BIT(ADMUX,REFS0);
		CLR_BIT(ADMUX,REFS1);
    #elif REFERENCE_SELECTION == V_REF_CAPACITOR
	    SET_BIT(ADMUX,REFS0);
		SET_BIT(ADMUX,REFS1);
	#else
		#warning "wrong selection"
	#endif
	
	#if ADC_PRESCALER == ADC_pre_2
	    CLR_BIT(ADCSRA,ADPS2);CLR_BIT(ADCSRA,ADPS1);SET_BIT(ADCSRA,ADPS0);
	#elif ADC_PRESCALER == ADC_pre_4
	    CLR_BIT(ADCSRA,ADPS2);SET_BIT(ADCSRA,ADPS1);CLR_BIT(ADCSRA,ADPS0);
	#elif ADC_PRESCALER == ADC_pre_8
	    CLR_BIT(ADCSRA,ADPS2);SET_BIT(ADCSRA,ADPS1);SET_BIT(ADCSRA,ADPS0);
	#elif ADC_PRESCALER == ADC_pre_16
	    SET_BIT(ADCSRA,ADPS2);CLR_BIT(ADCSRA,ADPS1);CLR_BIT(ADCSRA,ADPS0);
	#elif ADC_PRESCALER == ADC_pre_32
	    SET_BIT(ADCSRA,ADPS2);CLR_BIT(ADCSRA,ADPS1);SET_BIT(ADCSRA,ADPS0);
	#elif ADC_PRESCALER == ADC_pre_64
	    SET_BIT(ADCSRA,ADPS2);SET_BIT(ADCSRA,ADPS1);CLR_BIT(ADCSRA,ADPS0);
	#elif ADC_PRESCALER == ADC_pre_128
	    SET_BIT(ADCSRA,ADPS2);SET_BIT(ADCSRA,ADPS1);SET_BIT(ADCSRA,ADPS0);
	#else 
		#warning "worng selection"
	#endif
	
	#if ADC_AUTO_TRIGGER_SOURCE == FREE_RUNNING_MODE
        CLR_BIT(SFIOR,ADTS2); CLR_BIT(SFIOR,ADTS1); CLR_BIT(SFIOR,ADTS0);
	#elif ADC_AUTO_TRIGGER_SOURCE == ANALOG_COMPARATOR
	    CLR_BIT(SFIOR,ADTS2); CLR_BIT(SFIOR,ADTS1); SET_BIT(SFIOR,ADTS0);
	#elif ADC_AUTO_TRIGGER_SOURCE == EXT_INTERRUPT_REQUEST
	    CLR_BIT(SFIOR,ADTS2); SET_BIT(SFIOR,ADTS1); CLR_BIT(SFIOR,ADTS0);
	#elif ADC_AUTO_TRIGGER_SOURCE == T_C_0COMPARE_MATCH
	    CLR_BIT(SFIOR,ADTS2); SET_BIT(SFIOR,ADTS1); SET_BIT(SFIOR,ADTS0);
	#elif ADC_AUTO_TRIGGER_SOURCE == T_C_0_OVERFLOW
	    SET_BIT(SFIOR,ADTS2); CLR_BIT(SFIOR,ADTS1); CLR_BIT(SFIOR,ADTS0);
	#elif ADC_AUTO_TRIGGER_SOURCE == T_C_1_COMPARE_MATCH_B
	    SET_BIT(SFIOR,ADTS2); CLR_BIT(SFIOR,ADTS1); SET_BIT(SFIOR,ADTS0);
	#elif ADC_AUTO_TRIGGER_SOURCE == T_C_1_OVERFLOW
	    SET_BIT(SFIOR,ADTS2); SET_BIT(SFIOR,ADTS1); CLR_BIT(SFIOR,ADTS0);
	#elif ADC_AUTO_TRIGGER_SOURCE == T_C_1_CAPTURE_EVENT
	    SET_BIT(SFIOR,ADTS2); SET_BIT(SFIOR,ADTS1); SET_BIT(SFIOR,ADTS0);
	#else 
		#warning "wrong selection"
	#endif
	ADCSRA|=(ADC_ENABLE<<ADEN);
	ADCSRA|=(ADC_INTERRUPT_ENABLE<<ADIE);
	ADCSRA|=(Auto_Trigger_Enable<<ADATE);
	CLR_BIT(ADMUX,ADLAR);
}

u16 ADC_Read(u8 copy_ADC_channel)
{
	ADMUX|=(copy_ADC_channel<<MUX0);
	SET_BIT(ADCSRA,ADSC);
	while(GET_BIT(ADCSRA,ADIF)==1);
	
	return ADCL;
}



void (*PTF_ADC)(void);
void ADC_CallBack(void(*Ptr)(void))
{
	PTF_ADC=Ptr;
}

void __vector_16(void)
{
	PTF_ADC();
}











